CREATE TABLE T_USUARIO (
    ID_USUARIO   NUMBER NOT NULL PRIMARY KEY,
    NM_USUARIO   VARCHAR2(100) NOT NULL,
    NM_EMAIL     VARCHAR2(254) NOT NULL UNIQUE,
    DS_SENHA     VARCHAR2(20) NOT NULL
);

CREATE SEQUENCE SQ_T_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE T_TAREFA (
    ID_TAREFA     NUMBER NOT NULL PRIMARY KEY,
    ID_USUARIO    NUMBER NOT NULL,
    DS_TITULO     VARCHAR2(100) NOT NULL,
    DS_DESCRICAO  VARCHAR2(500),
    ST_CONCLUIDA  NUMBER(1) DEFAULT 0 CHECK (ST_CONCLUIDA IN (0,1)),

    CONSTRAINT FK_T_TAREFA_USUARIO
        FOREIGN KEY (ID_USUARIO) REFERENCES T_USUARIO(ID_USUARIO)
);

CREATE SEQUENCE SQ_T_TAREFA START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE T_META_MENSAL (
    ID_META_MENSAL        NUMBER PRIMARY KEY,
    ID_USUARIO            NUMBER NOT NULL,
    NR_MES                NUMBER NOT NULL,
    NR_ANO                NUMBER NOT NULL,
    NR_TAREFAS_CONCLUIDAS NUMBER DEFAULT 0 CHECK (NR_TAREFAS_CONCLUIDAS >= 0),
    NR_META_TAREFAS       NUMBER DEFAULT 15 CHECK (NR_META_TAREFAS > 0),

    CONSTRAINT FK_META_USUARIO
        FOREIGN KEY (ID_USUARIO) REFERENCES T_USUARIO(ID_USUARIO),

    CONSTRAINT UK_META_MES
        UNIQUE (ID_USUARIO, NR_MES, NR_ANO)
);

CREATE SEQUENCE SQ_T_META_MENSAL START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE T_PROJETO_PESSOAL (
    ID_PROJETO    NUMBER PRIMARY KEY,
    ID_USUARIO    NUMBER NOT NULL,
    DT_PERIODO    DATE NOT NULL,
    DS_TITULO     VARCHAR2(150) NOT NULL,
    DS_DESCRICAO  VARCHAR2(500),
    ST_CONCLUIDO  NUMBER(1) DEFAULT 0 CHECK (ST_CONCLUIDO IN (0,1)),
    DT_CONCLUSAO  DATE,

    CONSTRAINT FK_T_PROJ_USUARIO
        FOREIGN KEY (ID_USUARIO) REFERENCES T_USUARIO(ID_USUARIO)
);

CREATE SEQUENCE SQ_T_PROJETO_PESSOAL START WITH 1 INCREMENT BY 1 NOCACHE;