CREATE TABLE T_USUARIO (
    ID_USUARIO   NUMBER NOT NULL PRIMARY KEY,
    NM_USUARIO   VARCHAR2(100) NOT NULL,
    NM_EMAIL     VARCHAR2(254) NOT NULL UNIQUE,
    DS_SENHA     VARCHAR2(20) NOT NULL
);

CREATE SEQUENCE SQ_T_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE T_TAREFA (
    ID_TAREFA     NUMBER NOT NULL PRIMARY KEY,
    ID_USUARIO    NUMBER NOT NULL,
    DS_TITULO     VARCHAR2(100) NOT NULL,
    DS_DESCRICAO  VARCHAR2(500),
    ST_CONCLUIDA  NUMBER(1) DEFAULT 0 CHECK (ST_CONCLUIDA IN (0,1)),

    CONSTRAINT FK_T_TAREFA_USUARIO
        FOREIGN KEY (ID_USUARIO) REFERENCES T_USUARIO(ID_USUARIO)
);

CREATE SEQUENCE SQ_T_TAREFA START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE T_META (
    ID_META        NUMBER PRIMARY KEY,
    ID_USUARIO     NUMBER NOT NULL,
    NR_META_TOTAL  NUMBER DEFAULT 40 CHECK (NR_META_TOTAL > 0),
    NR_ATUAL       NUMBER DEFAULT 0 CHECK (NR_ATUAL >= 0),
    DT_CRIACAO     DATE DEFAULT SYSDATE NOT NULL,
    DT_CONCLUSAO   DATE,
    ST_CONCLUIDA   NUMBER(1) DEFAULT 0 CHECK (ST_CONCLUIDA IN (0,1)),

    CONSTRAINT FK_META_USUARIO
        FOREIGN KEY (ID_USUARIO) REFERENCES T_USUARIO(ID_USUARIO)
);

CREATE SEQUENCE SQ_T_META START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE T_PROJETO_PESSOAL (
    ID_PROJETO    NUMBER PRIMARY KEY,
    ID_USUARIO    NUMBER NOT NULL,
    DT_CRIACAO    DATE DEFAULT SYSDATE NOT NULL,
    DS_TITULO     VARCHAR2(150) NOT NULL,
    DS_DESCRICAO  VARCHAR2(500),
    ST_CONCLUIDO  NUMBER(1) DEFAULT 0 CHECK (ST_CONCLUIDO IN (0,1)),
    DT_CONCLUSAO  DATE,

    CONSTRAINT FK_T_PROJ_USUARIO
        FOREIGN KEY (ID_USUARIO) REFERENCES T_USUARIO(ID_USUARIO)
);

CREATE SEQUENCE SQ_T_PROJETO_PESSOAL START WITH 1 INCREMENT BY 1 NOCACHE;